<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20220504072921 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE ARCHIVEMDP (IDMdp INT AUTO_INCREMENT NOT NULL, MDP VARCHAR(512) DEFAULT NULL, DATECHANGEMENT DATETIME DEFAULT CURRENT_TIMESTAMP, ID_IDUSER INT DEFAULT NULL, INDEX FK_ARCHIVEMDP_USER (ID_IDUSER), PRIMARY KEY(IDMdp)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE CLIENT (TEL CHAR(10) DEFAULT NULL, EMAIL CHAR(50) DEFAULT NULL, RUE CHAR(32) DEFAULT NULL, CP CHAR(5) DEFAULT NULL, VILLE CHAR(32) DEFAULT NULL, DATEXPIRATION DATE DEFAULT NULL, CRYPTOGRAMME CHAR(32) DEFAULT NULL, NUMCARTE CHAR(50) DEFAULT NULL, ID INT NOT NULL, PRIMARY KEY(ID)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE COUTE (ID INT AUTO_INCREMENT NOT NULL, TARIF DOUBLE PRECISION DEFAULT NULL, ID_FORMULE INT DEFAULT NULL, ID_MODELE SMALLINT DEFAULT NULL, UNIQUE INDEX `index` (ID_MODELE), UNIQUE INDEX indexFormule (ID_FORMULE), PRIMARY KEY(ID)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE FORMULE (IDFormule INT AUTO_INCREMENT NOT NULL, LIBELLE CHAR(32) DEFAULT NULL, typeFormule VARCHAR(255) NOT NULL, UNIQUE INDEX IDFormule (IDFormule), PRIMARY KEY(IDFormule)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE FORMULEAVECCHAUFFEUR (LIEU VARCHAR(255) DEFAULT NULL, TARIF NUMERIC(6, 2) DEFAULT NULL, NUMLOCATION INT DEFAULT NULL, IDFormule INT NOT NULL, INDEX FK_FORMULEAVECCHAUFFEUR_LOCAVECCHAUFFEUR (NUMLOCATION), PRIMARY KEY(IDFormule)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE FORMULESANSCHAUFFEUR (DUREE INT DEFAULT NULL, NBKMSINCLUS INT DEFAULT NULL, NUMLOCATION INT DEFAULT NULL, IDFormule INT NOT NULL, INDEX FK_FORMULESANSCHAUFFEUR_LOCSANSCHAUFFEUR (NUMLOCATION), PRIMARY KEY(IDFormule)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE LOCATION (NUMLOCATION INT AUTO_INCREMENT NOT NULL, DATELOCATION DATE DEFAULT NULL, MONTANTREGLE CHAR(32) DEFAULT NULL, DATEHEUREDEPARTPREVU DATETIME DEFAULT NULL, DATEHEURERETOURPREVU DATETIME DEFAULT NULL, DATEHEUREDEPARTREEL DATETIME DEFAULT NULL, DATEHEURERETOURREEL DATETIME DEFAULT NULL, IMMATRICULATION CHAR(7) DEFAULT NULL, ID INT DEFAULT NULL, typeLoca VARCHAR(255) NOT NULL, INDEX FK_LOCATION_VEHICULE (IMMATRICULATION), INDEX FK_LOCATION_CLIENT (ID), PRIMARY KEY(NUMLOCATION)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE LOCAVECCHAUFFEUR (COMMENTAIRE CHAR(255) DEFAULT NULL, NUMLOCATION INT NOT NULL, PRIMARY KEY(NUMLOCATION)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE LOCSANSCHAUFFEUR (NBKMDEPART INT DEFAULT NULL, NBKMRETOUR INT DEFAULT NULL, NUMLOCATION INT NOT NULL, PRIMARY KEY(NUMLOCATION)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE MODELE (IdModele SMALLINT AUTO_INCREMENT NOT NULL, NOM CHAR(50) DEFAULT NULL, TARIFKMENPLUS NUMERIC(10, 2) DEFAULT NULL, PRIMARY KEY(IdModele)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE SALARIE (POSTE CHAR(32) DEFAULT NULL, ID INT NOT NULL, PRIMARY KEY(ID)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE VEHICULE (IMMATRICULATION CHAR(7) NOT NULL, COULEUR CHAR(32) DEFAULT NULL, ID SMALLINT DEFAULT NULL, INDEX FK_VEHICULE_MODELE (ID), PRIMARY KEY(IMMATRICULATION)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user (ID INT AUTO_INCREMENT NOT NULL, NOM CHAR(32) DEFAULT NULL, PRENOM CHAR(32) DEFAULT NULL, LOGIN CHAR(32) DEFAULT NULL, MOTDEPASSE VARCHAR(512) DEFAULT NULL, typeUser VARCHAR(255) NOT NULL, PRIMARY KEY(ID)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('ALTER TABLE ARCHIVEMDP ADD CONSTRAINT FK_AA529FAEF314B577 FOREIGN KEY (ID_IDUSER) REFERENCES user (ID)');
        $this->addSql('ALTER TABLE CLIENT ADD CONSTRAINT FK_37BCC3D311D3633A FOREIGN KEY (ID) REFERENCES user (ID) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE COUTE ADD CONSTRAINT FK_A8105CFB4C284A81 FOREIGN KEY (ID_FORMULE) REFERENCES FORMULE (IDFormule)');
        $this->addSql('ALTER TABLE COUTE ADD CONSTRAINT FK_A8105CFBBD4A17C6 FOREIGN KEY (ID_MODELE) REFERENCES MODELE (IdModele)');
        $this->addSql('ALTER TABLE FORMULEAVECCHAUFFEUR ADD CONSTRAINT FK_92CC0F762D6E0B7 FOREIGN KEY (NUMLOCATION) REFERENCES LOCAVECCHAUFFEUR (NUMLOCATION)');
        $this->addSql('ALTER TABLE FORMULEAVECCHAUFFEUR ADD CONSTRAINT FK_92CC0F7B62179F FOREIGN KEY (IDFormule) REFERENCES FORMULE (IDFormule) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE FORMULESANSCHAUFFEUR ADD CONSTRAINT FK_A178D1B962D6E0B7 FOREIGN KEY (NUMLOCATION) REFERENCES LOCSANSCHAUFFEUR (NUMLOCATION)');
        $this->addSql('ALTER TABLE FORMULESANSCHAUFFEUR ADD CONSTRAINT FK_A178D1B9B62179F FOREIGN KEY (IDFormule) REFERENCES FORMULE (IDFormule) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE LOCATION ADD CONSTRAINT FK_98AD1587DD9E068D FOREIGN KEY (IMMATRICULATION) REFERENCES VEHICULE (IMMATRICULATION)');
        $this->addSql('ALTER TABLE LOCATION ADD CONSTRAINT FK_98AD158711D3633A FOREIGN KEY (ID) REFERENCES CLIENT (ID)');
        $this->addSql('ALTER TABLE LOCAVECCHAUFFEUR ADD CONSTRAINT FK_59EFC79862D6E0B7 FOREIGN KEY (NUMLOCATION) REFERENCES LOCATION (NUMLOCATION) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE LOCSANSCHAUFFEUR ADD CONSTRAINT FK_F1BBD6D662D6E0B7 FOREIGN KEY (NUMLOCATION) REFERENCES LOCATION (NUMLOCATION) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE SALARIE ADD CONSTRAINT FK_BDCBC40011D3633A FOREIGN KEY (ID) REFERENCES user (ID) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE VEHICULE ADD CONSTRAINT FK_EF1C635111D3633A FOREIGN KEY (ID) REFERENCES MODELE (IdModele)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE LOCATION DROP FOREIGN KEY FK_98AD158711D3633A');
        $this->addSql('ALTER TABLE COUTE DROP FOREIGN KEY FK_A8105CFB4C284A81');
        $this->addSql('ALTER TABLE FORMULEAVECCHAUFFEUR DROP FOREIGN KEY FK_92CC0F7B62179F');
        $this->addSql('ALTER TABLE FORMULESANSCHAUFFEUR DROP FOREIGN KEY FK_A178D1B9B62179F');
        $this->addSql('ALTER TABLE LOCAVECCHAUFFEUR DROP FOREIGN KEY FK_59EFC79862D6E0B7');
        $this->addSql('ALTER TABLE LOCSANSCHAUFFEUR DROP FOREIGN KEY FK_F1BBD6D662D6E0B7');
        $this->addSql('ALTER TABLE FORMULEAVECCHAUFFEUR DROP FOREIGN KEY FK_92CC0F762D6E0B7');
        $this->addSql('ALTER TABLE FORMULESANSCHAUFFEUR DROP FOREIGN KEY FK_A178D1B962D6E0B7');
        $this->addSql('ALTER TABLE COUTE DROP FOREIGN KEY FK_A8105CFBBD4A17C6');
        $this->addSql('ALTER TABLE VEHICULE DROP FOREIGN KEY FK_EF1C635111D3633A');
        $this->addSql('ALTER TABLE LOCATION DROP FOREIGN KEY FK_98AD1587DD9E068D');
        $this->addSql('ALTER TABLE ARCHIVEMDP DROP FOREIGN KEY FK_AA529FAEF314B577');
        $this->addSql('ALTER TABLE CLIENT DROP FOREIGN KEY FK_37BCC3D311D3633A');
        $this->addSql('ALTER TABLE SALARIE DROP FOREIGN KEY FK_BDCBC40011D3633A');
        $this->addSql('DROP TABLE ARCHIVEMDP');
        $this->addSql('DROP TABLE CLIENT');
        $this->addSql('DROP TABLE COUTE');
        $this->addSql('DROP TABLE FORMULE');
        $this->addSql('DROP TABLE FORMULEAVECCHAUFFEUR');
        $this->addSql('DROP TABLE FORMULESANSCHAUFFEUR');
        $this->addSql('DROP TABLE LOCATION');
        $this->addSql('DROP TABLE LOCAVECCHAUFFEUR');
        $this->addSql('DROP TABLE LOCSANSCHAUFFEUR');
        $this->addSql('DROP TABLE MODELE');
        $this->addSql('DROP TABLE SALARIE');
        $this->addSql('DROP TABLE VEHICULE');
        $this->addSql('DROP TABLE user');
    }
}
